#!/bin/bash

if [[ $# = 1 && -r "$1" ]]; then
  c++filt <$1 | perl -pe 's/[(]sc_dt::sc_\w_mode[)]//g;s/, +/,/g;'
elif [[ $# = 0 ]]; then
  c++filt | perl -pe 's/[(]sc_dt::sc_\w_mode[)]//g;s/, +/,/g;'
else
  echo "SYNTAX: filter [FILE]"
fi
